# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-26 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200425_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
