# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-26 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200425_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price']},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=850),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.CharField(choices=[('europe', 'Europe'), ('america', 'America'), ('rest of world', 'Rest Of World')], default='europe', max_length=13),
        ),
    ]
